name: Deploy Minesweeper
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install and Upgrade Flet
        run: |
          pip install --upgrade pip
          pip install --upgrade flet
      - name: Build Web App
        # This is the crucial change
        run: python -m flet build web --base-href /minesweeper/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web