name: Deploy Minesweeper
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install and Upgrade Flet
        run: |
          pip install --upgrade pip
          pip install --upgrade flet
      - name: Build Web App
        # We ensure we are running the build command with the latest tools
        run: flet build web --base-href /minesweeper-game/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web